//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectTimetable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int Id { get; set; }
        public string DayNumber { get; set; }
        public int PairNumber { get; set; }
        public string WeekNumber { get; set; }
        public string GroupId { get; set; }
        public string Subgroup { get; set; }
        public string ShortSubjectName { get; set; }
        public string AudienceNumber { get; set; }
        public string TeacherId { get; set; }
        public string ShortPairtypeName { get; set; }
    
        public virtual Audience Audience { get; set; }
        public virtual Groups Groups { get; set; }
        public virtual PairsNumber PairsNumber { get; set; }
        public virtual PairTypes PairTypes { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
